export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const CHANGE_TABS = 'CHANGE_TABS';
export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';
export const TOGGLE_RADIO_BUTTONS = 'TOGGLE_RADIO_BUTTONS';
